package global

import "time"

// ZoneOffset - timezone name to time difference as Duration
var ZoneOffset = map[string]time.Duration{
	"Africa/Abidjan":                   time.Duration(0),
	"Africa/Accra":                     time.Duration(0),
	"Africa/Addis_Ababa":               (time.Hour * time.Duration(3)),
	"Africa/Algiers":                   (time.Hour * time.Duration(1)),
	"Africa/Asmara":                    (time.Hour * time.Duration(3)),
	"Africa/Bamako":                    time.Duration(0),
	"Africa/Bangui":                    (time.Hour * time.Duration(1)),
	"Africa/Banjul":                    time.Duration(0),
	"Africa/Bissau":                    time.Duration(0),
	"Africa/Blantyre":                  (time.Hour * time.Duration(2)),
	"Africa/Brazzaville":               (time.Hour * time.Duration(1)),
	"Africa/Bujumbura":                 (time.Hour * time.Duration(2)),
	"Africa/Cairo":                     (time.Hour * time.Duration(2)),
	"Africa/Casablanca":                (time.Hour * time.Duration(1)),
	"Africa/Ceuta":                     (time.Hour * time.Duration(1)),
	"Africa/Conakry":                   time.Duration(0),
	"Africa/Dakar":                     time.Duration(0),
	"Africa/Dar_es_Salaam":             (time.Hour * time.Duration(3)),
	"Africa/Djibouti":                  (time.Hour * time.Duration(3)),
	"Africa/Douala":                    (time.Hour * time.Duration(1)),
	"Africa/El_Aaiun":                  time.Duration(0),
	"Africa/Freetown":                  time.Duration(0),
	"Africa/Gaborone":                  (time.Hour * time.Duration(2)),
	"Africa/Harare":                    (time.Hour * time.Duration(2)),
	"Africa/Johannesburg":              (time.Hour * time.Duration(2)),
	"Africa/Juba":                      (time.Hour * time.Duration(3)),
	"Africa/Kampala":                   (time.Hour * time.Duration(3)),
	"Africa/Khartoum":                  (time.Hour * time.Duration(2)),
	"Africa/Kigali":                    (time.Hour * time.Duration(2)),
	"Africa/Kinshasa":                  (time.Hour * time.Duration(1)),
	"Africa/Lagos":                     (time.Hour * time.Duration(1)),
	"Africa/Libreville":                (time.Hour * time.Duration(1)),
	"Africa/Lome":                      time.Duration(0),
	"Africa/Luanda":                    (time.Hour * time.Duration(1)),
	"Africa/Lubumbashi":                (time.Hour * time.Duration(2)),
	"Africa/Lusaka":                    (time.Hour * time.Duration(2)),
	"Africa/Malabo":                    (time.Hour * time.Duration(1)),
	"Africa/Maputo":                    (time.Hour * time.Duration(2)),
	"Africa/Maseru":                    (time.Hour * time.Duration(2)),
	"Africa/Mbabane":                   (time.Hour * time.Duration(2)),
	"Africa/Mogadishu":                 (time.Hour * time.Duration(3)),
	"Africa/Monrovia":                  time.Duration(0),
	"Africa/Nairobi":                   (time.Hour * time.Duration(3)),
	"Africa/Ndjamena":                  (time.Hour * time.Duration(1)),
	"Africa/Niamey":                    (time.Hour * time.Duration(1)),
	"Africa/Nouakchott":                time.Duration(0),
	"Africa/Ouagadougou":               time.Duration(0),
	"Africa/Porto-Novo":                (time.Hour * time.Duration(1)),
	"Africa/Sao_Tome":                  time.Duration(0),
	"Africa/Timbuktu":                  time.Duration(0),
	"Africa/Tripoli":                   (time.Hour * time.Duration(2)),
	"Africa/Tunis":                     (time.Hour * time.Duration(1)),
	"Africa/Windhoek":                  (time.Hour * time.Duration(2)),
	"America/Adak":                     (time.Hour * time.Duration(-10)),
	"America/Anchorage":                (time.Hour * time.Duration(-9)),
	"America/Anguilla":                 (time.Hour * time.Duration(-4)),
	"America/Antigua":                  (time.Hour * time.Duration(-4)),
	"America/Araguaina":                (time.Hour * time.Duration(-3)),
	"America/Argentina/Buenos_Aires":   (time.Hour * time.Duration(-3)),
	"America/Argentina/Catamarca":      (time.Hour * time.Duration(-3)),
	"America/Argentina/ComodRivadavia": (time.Hour * time.Duration(-3)),
	"America/Argentina/Cordoba":        (time.Hour * time.Duration(-3)),
	"America/Argentina/Jujuy":          (time.Hour * time.Duration(-3)),
	"America/Argentina/La_Rioja":       (time.Hour * time.Duration(-3)),
	"America/Argentina/Mendoza":        (time.Hour * time.Duration(-3)),
	"America/Argentina/Rio_Gallegos":   (time.Hour * time.Duration(-3)),
	"America/Argentina/Salta":          (time.Hour * time.Duration(-3)),
	"America/Argentina/San_Juan":       (time.Hour * time.Duration(-3)),
	"America/Argentina/San_Luis":       (time.Hour * time.Duration(-3)),
	"America/Argentina/Tucuman":        (time.Hour * time.Duration(-3)),
	"America/Argentina/Ushuaia":        (time.Hour * time.Duration(-3)),
	"America/Aruba":                    (time.Hour * time.Duration(-4)),
	"America/Asuncion":                 (time.Hour * time.Duration(-4)),
	"America/Atikokan":                 (time.Hour * time.Duration(-5)),
	"America/Atka":                     (time.Hour * time.Duration(-10)),
	"America/Bahia":                    (time.Hour * time.Duration(-3)),
	"America/Bahia_Banderas":           (time.Hour * time.Duration(-6)),
	"America/Barbados":                 (time.Hour * time.Duration(-4)),
	"America/Belem":                    (time.Hour * time.Duration(-3)),
	"America/Belize":                   (time.Hour * time.Duration(-6)),
	"America/Blanc-Sablon":             (time.Hour * time.Duration(-4)),
	"America/Boa_Vista":                (time.Hour * time.Duration(-4)),
	"America/Bogota":                   (time.Hour * time.Duration(-5)),
	"America/Boise":                    (time.Hour * time.Duration(-7)),
	"America/Buenos_Aires":             (time.Hour * time.Duration(-3)),
	"America/Cambridge_Bay":            (time.Hour * time.Duration(-7)),
	"America/Campo_Grande":             (time.Hour * time.Duration(-4)),
	"America/Cancun":                   (time.Hour * time.Duration(-5)),
	"America/Caracas":                  (time.Hour * time.Duration(-4)),
	"America/Catamarca":                (time.Hour * time.Duration(-3)),
	"America/Cayenne":                  (time.Hour * time.Duration(-3)),
	"America/Cayman":                   (time.Hour * time.Duration(-5)),
	"America/Chicago":                  (time.Hour * time.Duration(-6)),
	"America/Chihuahua":                (time.Hour * time.Duration(-7)),
	"America/Coral_Harbour":            (time.Hour * time.Duration(-5)),
	"America/Cordoba":                  (time.Hour * time.Duration(-3)),
	"America/Costa_Rica":               (time.Hour * time.Duration(-6)),
	"America/Creston":                  (time.Hour * time.Duration(-7)),
	"America/Cuiaba":                   (time.Hour * time.Duration(-4)),
	"America/Curacao":                  (time.Hour * time.Duration(-4)),
	"America/Danmarkshavn":             time.Duration(0),
	"America/Dawson":                   (time.Hour * time.Duration(-8)),
	"America/Dawson_Creek":             (time.Hour * time.Duration(-7)),
	"America/Denver":                   (time.Hour * time.Duration(-7)),
	"America/Detroit":                  (time.Hour * time.Duration(-5)),
	"America/Dominica":                 (time.Hour * time.Duration(-4)),
	"America/Edmonton":                 (time.Hour * time.Duration(-7)),
	"America/Eirunepe":                 (time.Hour * time.Duration(-5)),
	"America/El_Salvador":              (time.Hour * time.Duration(-6)),
	"America/Ensenada":                 (time.Hour * time.Duration(-8)),
	"America/Fort_Nelson":              (time.Hour * time.Duration(-7)),
	"America/Fort_Wayne":               (time.Hour * time.Duration(-5)),
	"America/Fortaleza":                (time.Hour * time.Duration(-3)),
	"America/Glace_Bay":                (time.Hour * time.Duration(-4)),
	"America/Godthab":                  (time.Hour * time.Duration(-3)),
	"America/Goose_Bay":                (time.Hour * time.Duration(-4)),
	"America/Grand_Turk":               (time.Hour * time.Duration(-5)),
	"America/Grenada":                  (time.Hour * time.Duration(-4)),
	"America/Guadeloupe":               (time.Hour * time.Duration(-4)),
	"America/Guatemala":                (time.Hour * time.Duration(-6)),
	"America/Guayaquil":                (time.Hour * time.Duration(-5)),
	"America/Guyana":                   (time.Hour * time.Duration(-4)),
	"America/Halifax":                  (time.Hour * time.Duration(-4)),
	"America/Havana":                   (time.Hour * time.Duration(-5)),
	"America/Hermosillo":               (time.Hour * time.Duration(-7)),
	"America/Indiana/Indianapolis":     (time.Hour * time.Duration(-5)),
	"America/Indiana/Knox":             (time.Hour * time.Duration(-6)),
	"America/Indiana/Marengo":          (time.Hour * time.Duration(-5)),
	"America/Indiana/Petersburg":       (time.Hour * time.Duration(-5)),
	"America/Indiana/Tell_City":        (time.Hour * time.Duration(-6)),
	"America/Indiana/Vevay":            (time.Hour * time.Duration(-5)),
	"America/Indiana/Vincennes":        (time.Hour * time.Duration(-5)),
	"America/Indiana/Winamac":          (time.Hour * time.Duration(-5)),
	"America/Indianapolis":             (time.Hour * time.Duration(-5)),
	"America/Inuvik":                   (time.Hour * time.Duration(-7)),
	"America/Iqaluit":                  (time.Hour * time.Duration(-5)),
	"America/Jamaica":                  (time.Hour * time.Duration(-5)),
	"America/Jujuy":                    (time.Hour * time.Duration(-3)),
	"America/Juneau":                   (time.Hour * time.Duration(-9)),
	"America/Kentucky/Louisville":      (time.Hour * time.Duration(-5)),
	"America/Kentucky/Monticello":      (time.Hour * time.Duration(-5)),
	"America/Knox_IN":                  (time.Hour * time.Duration(-6)),
	"America/Kralendijk":               (time.Hour * time.Duration(-4)),
	"America/La_Paz":                   (time.Hour * time.Duration(-4)),
	"America/Lima":                     (time.Hour * time.Duration(-5)),
	"America/Los_Angeles":              (time.Hour * time.Duration(-8)),
	"America/Louisville":               (time.Hour * time.Duration(-5)),
	"America/Lower_Princes":            (time.Hour * time.Duration(-4)),
	"America/Maceio":                   (time.Hour * time.Duration(-3)),
	"America/Managua":                  (time.Hour * time.Duration(-6)),
	"America/Manaus":                   (time.Hour * time.Duration(-4)),
	"America/Marigot":                  (time.Hour * time.Duration(-4)),
	"America/Martinique":               (time.Hour * time.Duration(-4)),
	"America/Matamoros":                (time.Hour * time.Duration(-6)),
	"America/Mazatlan":                 (time.Hour * time.Duration(-7)),
	"America/Mendoza":                  (time.Hour * time.Duration(-3)),
	"America/Menominee":                (time.Hour * time.Duration(-6)),
	"America/Merida":                   (time.Hour * time.Duration(-6)),
	"America/Metlakatla":               (time.Hour * time.Duration(-9)),
	"America/Mexico_City":              (time.Hour * time.Duration(-6)),
	"America/Miquelon":                 (time.Hour * time.Duration(-3)),
	"America/Moncton":                  (time.Hour * time.Duration(-4)),
	"America/Monterrey":                (time.Hour * time.Duration(-6)),
	"America/Montevideo":               (time.Hour * time.Duration(-3)),
	"America/Montreal":                 (time.Hour * time.Duration(-5)),
	"America/Montserrat":               (time.Hour * time.Duration(-4)),
	"America/Nassau":                   (time.Hour * time.Duration(-5)),
	"America/New_York":                 (time.Hour * time.Duration(-5)),
	"America/Nipigon":                  (time.Hour * time.Duration(-5)),
	"America/Nome":                     (time.Hour * time.Duration(-9)),
	"America/Noronha":                  (time.Hour * time.Duration(-2)),
	"America/North_Dakota/Beulah":      (time.Hour * time.Duration(-6)),
	"America/North_Dakota/Center":      (time.Hour * time.Duration(-6)),
	"America/North_Dakota/New_Salem":   (time.Hour * time.Duration(-6)),
	"America/Ojinaga":                  (time.Hour * time.Duration(-7)),
	"America/Panama":                   (time.Hour * time.Duration(-5)),
	"America/Pangnirtung":              (time.Hour * time.Duration(-5)),
	"America/Paramaribo":               (time.Hour * time.Duration(-3)),
	"America/Phoenix":                  (time.Hour * time.Duration(-7)),
	"America/Port_of_Spain":            (time.Hour * time.Duration(-4)),
	"America/Port-au-Prince":           (time.Hour * time.Duration(-5)),
	"America/Porto_Acre":               (time.Hour * time.Duration(-5)),
	"America/Porto_Velho":              (time.Hour * time.Duration(-4)),
	"America/Puerto_Rico":              (time.Hour * time.Duration(-4)),
	"America/Punta_Arenas":             (time.Hour * time.Duration(-3)),
	"America/Rainy_River":              (time.Hour * time.Duration(-6)),
	"America/Rankin_Inlet":             (time.Hour * time.Duration(-6)),
	"America/Recife":                   (time.Hour * time.Duration(-3)),
	"America/Regina":                   (time.Hour * time.Duration(-6)),
	"America/Resolute":                 (time.Hour * time.Duration(-6)),
	"America/Rio_Branco":               (time.Hour * time.Duration(-5)),
	"America/Rosario":                  (time.Hour * time.Duration(-3)),
	"America/Santa_Isabel":             (time.Hour * time.Duration(-8)),
	"America/Santarem":                 (time.Hour * time.Duration(-3)),
	"America/Santiago":                 (time.Hour * time.Duration(-4)),
	"America/Santo_Domingo":            (time.Hour * time.Duration(-4)),
	"America/Sao_Paulo":                (time.Hour * time.Duration(-3)),
	"America/Scoresbysund":             (time.Hour * time.Duration(-1)),
	"America/Shiprock":                 (time.Hour * time.Duration(-7)),
	"America/Sitka":                    (time.Hour * time.Duration(-9)),
	"America/St_Barthelemy":            (time.Hour * time.Duration(-4)),
	"America/St_Johns":                 (time.Hour * time.Duration(-3)) + (time.Minute * time.Duration(30)),
	"America/St_Kitts":                 (time.Hour * time.Duration(-4)),
	"America/St_Lucia":                 (time.Hour * time.Duration(-4)),
	"America/St_Thomas":                (time.Hour * time.Duration(-4)),
	"America/St_Vincent":               (time.Hour * time.Duration(-4)),
	"America/Swift_Current":            (time.Hour * time.Duration(-6)),
	"America/Tegucigalpa":              (time.Hour * time.Duration(-6)),
	"America/Thule":                    (time.Hour * time.Duration(-4)),
	"America/Thunder_Bay":              (time.Hour * time.Duration(-5)),
	"America/Tijuana":                  (time.Hour * time.Duration(-8)),
	"America/Toronto":                  (time.Hour * time.Duration(-5)),
	"America/Tortola":                  (time.Hour * time.Duration(-4)),
	"America/Vancouver":                (time.Hour * time.Duration(-8)),
	"America/Virgin":                   (time.Hour * time.Duration(-4)),
	"America/Whitehorse":               (time.Hour * time.Duration(-8)),
	"America/Winnipeg":                 (time.Hour * time.Duration(-6)),
	"America/Yakutat":                  (time.Hour * time.Duration(-9)),
	"America/Yellowknife":              (time.Hour * time.Duration(-7)),
	"Antarctica/Casey":                 (time.Hour * time.Duration(11)),
	"Antarctica/Davis":                 (time.Hour * time.Duration(7)),
	"Antarctica/DumontDUrville":        (time.Hour * time.Duration(10)),
	"Antarctica/Macquarie":             (time.Hour * time.Duration(11)),
	"Antarctica/Mawson":                (time.Hour * time.Duration(5)),
	"Antarctica/McMurdo":               (time.Hour * time.Duration(12)),
	"Antarctica/Palmer":                (time.Hour * time.Duration(-3)),
	"Antarctica/Rothera":               (time.Hour * time.Duration(-3)),
	"Antarctica/South_Pole":            (time.Hour * time.Duration(12)),
	"Antarctica/Syowa":                 (time.Hour * time.Duration(3)),
	"Antarctica/Troll":                 time.Duration(0),
	"Antarctica/Vostok":                (time.Hour * time.Duration(6)),
	"Arctic/Longyearbyen":              (time.Hour * time.Duration(1)),
	"Asia/Aden":                        (time.Hour * time.Duration(3)),
	"Asia/Almaty":                      (time.Hour * time.Duration(6)),
	"Asia/Amman":                       (time.Hour * time.Duration(2)),
	"Asia/Anadyr":                      (time.Hour * time.Duration(12)),
	"Asia/Aqtau":                       (time.Hour * time.Duration(5)),
	"Asia/Aqtobe":                      (time.Hour * time.Duration(5)),
	"Asia/Ashgabat":                    (time.Hour * time.Duration(5)),
	"Asia/Ashkhabad":                   (time.Hour * time.Duration(5)),
	"Asia/Atyrau":                      (time.Hour * time.Duration(5)),
	"Asia/Baghdad":                     (time.Hour * time.Duration(3)),
	"Asia/Bahrain":                     (time.Hour * time.Duration(3)),
	"Asia/Baku":                        (time.Hour * time.Duration(4)),
	"Asia/Bangkok":                     (time.Hour * time.Duration(7)),
	"Asia/Barnaul":                     (time.Hour * time.Duration(7)),
	"Asia/Beirut":                      (time.Hour * time.Duration(2)),
	"Asia/Bishkek":                     (time.Hour * time.Duration(6)),
	"Asia/Brunei":                      (time.Hour * time.Duration(8)),
	"Asia/Calcutta":                    (time.Hour * time.Duration(5)) + (time.Minute * time.Duration(30)),
	"Asia/Chita":                       (time.Hour * time.Duration(9)),
	"Asia/Choibalsan":                  (time.Hour * time.Duration(8)),
	"Asia/Chongqing":                   (time.Hour * time.Duration(8)),
	"Asia/Chungking":                   (time.Hour * time.Duration(8)),
	"Asia/Colombo":                     (time.Hour * time.Duration(5)) + (time.Minute * time.Duration(30)),
	"Asia/Dacca":                       (time.Hour * time.Duration(6)),
	"Asia/Damascus":                    (time.Hour * time.Duration(2)),
	"Asia/Dhaka":                       (time.Hour * time.Duration(6)),
	"Asia/Dili":                        (time.Hour * time.Duration(9)),
	"Asia/Dubai":                       (time.Hour * time.Duration(4)),
	"Asia/Dushanbe":                    (time.Hour * time.Duration(5)),
	"Asia/Famagusta":                   (time.Hour * time.Duration(2)),
	"Asia/Gaza":                        (time.Hour * time.Duration(2)),
	"Asia/Harbin":                      (time.Hour * time.Duration(8)),
	"Asia/Hebron":                      (time.Hour * time.Duration(2)),
	"Asia/Ho_Chi_Minh":                 (time.Hour * time.Duration(7)),
	"Asia/Hong_Kong":                   (time.Hour * time.Duration(8)),
	"Asia/Hovd":                        (time.Hour * time.Duration(7)),
	"Asia/Irkutsk":                     (time.Hour * time.Duration(8)),
	"Asia/Istanbul":                    (time.Hour * time.Duration(3)),
	"Asia/Jakarta":                     (time.Hour * time.Duration(7)),
	"Asia/Jayapura":                    (time.Hour * time.Duration(9)),
	"Asia/Jerusalem":                   (time.Hour * time.Duration(2)),
	"Asia/Kabul":                       (time.Hour * time.Duration(4)) + (time.Minute * time.Duration(30)),
	"Asia/Kamchatka":                   (time.Hour * time.Duration(12)),
	"Asia/Karachi":                     (time.Hour * time.Duration(5)),
	"Asia/Kashgar":                     (time.Hour * time.Duration(6)),
	"Asia/Kathmandu":                   (time.Hour * time.Duration(5)) + (time.Minute * time.Duration(45)),
	"Asia/Katmandu":                    (time.Hour * time.Duration(5)) + (time.Minute * time.Duration(45)),
	"Asia/Khandyga":                    (time.Hour * time.Duration(9)),
	"Asia/Kolkata":                     (time.Hour * time.Duration(5)) + (time.Minute * time.Duration(30)),
	"Asia/Krasnoyarsk":                 (time.Hour * time.Duration(7)),
	"Asia/Kuala_Lumpur":                (time.Hour * time.Duration(8)),
	"Asia/Kuching":                     (time.Hour * time.Duration(8)),
	"Asia/Kuwait":                      (time.Hour * time.Duration(3)),
	"Asia/Macao":                       (time.Hour * time.Duration(8)),
	"Asia/Macau":                       (time.Hour * time.Duration(8)),
	"Asia/Magadan":                     (time.Hour * time.Duration(11)),
	"Asia/Makassar":                    (time.Hour * time.Duration(8)),
	"Asia/Manila":                      (time.Hour * time.Duration(8)),
	"Asia/Muscat":                      (time.Hour * time.Duration(4)),
	"Asia/Novokuznetsk":                (time.Hour * time.Duration(7)),
	"Asia/Novosibirsk":                 (time.Hour * time.Duration(7)),
	"Asia/Omsk":                        (time.Hour * time.Duration(6)),
	"Asia/Oral":                        (time.Hour * time.Duration(5)),
	"Asia/Phnom_Penh":                  (time.Hour * time.Duration(7)),
	"Asia/Pontianak":                   (time.Hour * time.Duration(7)),
	"Asia/Pyongyang":                   (time.Hour * time.Duration(9)),
	"Asia/Qatar":                       (time.Hour * time.Duration(3)),
	"Asia/Qyzylorda":                   (time.Hour * time.Duration(5)),
	"Asia/Rangoon":                     (time.Hour * time.Duration(6)) + (time.Minute * time.Duration(30)),
	"Asia/Riyadh":                      (time.Hour * time.Duration(3)),
	"Asia/Saigon":                      (time.Hour * time.Duration(7)),
	"Asia/Sakhalin":                    (time.Hour * time.Duration(11)),
	"Asia/Samarkand":                   (time.Hour * time.Duration(5)),
	"Asia/Seoul":                       (time.Hour * time.Duration(9)),
	"Asia/Shanghai":                    (time.Hour * time.Duration(8)),
	"Asia/Singapore":                   (time.Hour * time.Duration(8)),
	"Asia/Srednekolymsk":               (time.Hour * time.Duration(11)),
	"Asia/Taipei":                      (time.Hour * time.Duration(8)),
	"Asia/Tashkent":                    (time.Hour * time.Duration(5)),
	"Asia/Tbilisi":                     (time.Hour * time.Duration(4)),
	"Asia/Tehran":                      (time.Hour * time.Duration(3)) + (time.Minute * time.Duration(30)),
	"Asia/Tel_Aviv":                    (time.Hour * time.Duration(2)),
	"Asia/Thimbu":                      (time.Hour * time.Duration(6)),
	"Asia/Thimphu":                     (time.Hour * time.Duration(6)),
	"Asia/Tokyo":                       (time.Hour * time.Duration(9)),
	"Asia/Tomsk":                       (time.Hour * time.Duration(7)),
	"Asia/Ujung_Pandang":               (time.Hour * time.Duration(8)),
	"Asia/Ulaanbaatar":                 (time.Hour * time.Duration(8)),
	"Asia/Ulan_Bator":                  (time.Hour * time.Duration(8)),
	"Asia/Urumqi":                      (time.Hour * time.Duration(6)),
	"Asia/Ust-Nera":                    (time.Hour * time.Duration(10)),
	"Asia/Vientiane":                   (time.Hour * time.Duration(7)),
	"Asia/Vladivostok":                 (time.Hour * time.Duration(10)),
	"Asia/Yakutsk":                     (time.Hour * time.Duration(9)),
	"Asia/Yangon":                      (time.Hour * time.Duration(6)) + (time.Minute * time.Duration(30)),
	"Asia/Yekaterinburg":               (time.Hour * time.Duration(5)),
	"Asia/Yerevan":                     (time.Hour * time.Duration(4)),
	"Atlantic/Azores":                  (time.Hour * time.Duration(-1)),
	"Atlantic/Bermuda":                 (time.Hour * time.Duration(-4)),
	"Atlantic/Canary":                  time.Duration(0),
	"Atlantic/Cape_Verde":              (time.Hour * time.Duration(-1)),
	"Atlantic/Faeroe":                  time.Duration(0),
	"Atlantic/Faroe":                   time.Duration(0),
	"Atlantic/Jan_Mayen":               (time.Hour * time.Duration(1)),
	"Atlantic/Madeira":                 time.Duration(0),
	"Atlantic/Reykjavik":               time.Duration(0),
	"Atlantic/South_Georgia":           (time.Hour * time.Duration(-2)),
	"Atlantic/St_Helena":               time.Duration(0),
	"Atlantic/Stanley":                 (time.Hour * time.Duration(-3)),
	"Australia/Adelaide":               (time.Hour * time.Duration(9)) + (time.Minute * time.Duration(30)),
	"Australia/Brisbane":               (time.Hour * time.Duration(10)),
	"Australia/Broken_Hill":            (time.Hour * time.Duration(9)) + (time.Minute * time.Duration(30)),
	"Australia/Canberra":               (time.Hour * time.Duration(10)),
	"Australia/Currie":                 (time.Hour * time.Duration(10)),
	"Australia/Darwin":                 (time.Hour * time.Duration(9)) + (time.Minute * time.Duration(30)),
	"Australia/Eucla":                  (time.Hour * time.Duration(8)) + (time.Minute * time.Duration(45)),
	"Australia/Hobart":                 (time.Hour * time.Duration(10)),
	"Australia/Lindeman":               (time.Hour * time.Duration(10)),
	"Australia/Lord_Howe":              (time.Hour * time.Duration(+10)) + (time.Minute * time.Duration(30)),
	"Australia/Melbourne":              (time.Hour * time.Duration(10)),
	"Australia/Perth":                  (time.Hour * time.Duration(8)),
	"Australia/Sydney":                 (time.Hour * time.Duration(10)),
	"Australia/Yancowinna":             (time.Hour * time.Duration(9)) + (time.Minute * time.Duration(30)),
	"Etc/GMT":                          time.Duration(0),
	"Etc/GMT+0":                        time.Duration(0),
	"Etc/GMT+1":                        (time.Hour * time.Duration(-1)),
	"Etc/GMT+10":                       (time.Hour * time.Duration(-10)),
	"Etc/GMT+11":                       (time.Hour * time.Duration(-11)),
	"Etc/GMT+12":                       (time.Hour * time.Duration(-12)),
	"Etc/GMT+2":                        (time.Hour * time.Duration(-2)),
	"Etc/GMT+3":                        (time.Hour * time.Duration(-3)),
	"Etc/GMT+4":                        (time.Hour * time.Duration(-4)),
	"Etc/GMT+5":                        (time.Hour * time.Duration(-5)),
	"Etc/GMT+6":                        (time.Hour * time.Duration(-6)),
	"Etc/GMT+7":                        (time.Hour * time.Duration(-7)),
	"Etc/GMT+8":                        (time.Hour * time.Duration(-8)),
	"Etc/GMT+9":                        (time.Hour * time.Duration(-9)),
	"Etc/GMT0":                         time.Duration(0),
	"Etc/GMT-0":                        time.Duration(0),
	"Etc/GMT-1":                        (time.Hour * time.Duration(1)),
	"Etc/GMT-10":                       (time.Hour * time.Duration(10)),
	"Etc/GMT-11":                       (time.Hour * time.Duration(11)),
	"Etc/GMT-12":                       (time.Hour * time.Duration(12)),
	"Etc/GMT-13":                       (time.Hour * time.Duration(13)),
	"Etc/GMT-14":                       (time.Hour * time.Duration(14)),
	"Etc/GMT-2":                        (time.Hour * time.Duration(2)),
	"Etc/GMT-3":                        (time.Hour * time.Duration(3)),
	"Etc/GMT-4":                        (time.Hour * time.Duration(4)),
	"Etc/GMT-5":                        (time.Hour * time.Duration(5)),
	"Etc/GMT-6":                        (time.Hour * time.Duration(6)),
	"Etc/GMT-7":                        (time.Hour * time.Duration(7)),
	"Etc/GMT-8":                        (time.Hour * time.Duration(8)),
	"Etc/GMT-9":                        (time.Hour * time.Duration(9)),
	"Etc/UTC":                          time.Duration(0),
	"Europe/Amsterdam":                 (time.Hour * time.Duration(1)),
	"Europe/Andorra":                   (time.Hour * time.Duration(1)),
	"Europe/Astrakhan":                 (time.Hour * time.Duration(4)),
	"Europe/Athens":                    (time.Hour * time.Duration(2)),
	"Europe/Belfast":                   time.Duration(0),
	"Europe/Belgrade":                  (time.Hour * time.Duration(1)),
	"Europe/Berlin":                    (time.Hour * time.Duration(1)),
	"Europe/Bratislava":                (time.Hour * time.Duration(1)),
	"Europe/Brussels":                  (time.Hour * time.Duration(1)),
	"Europe/Bucharest":                 (time.Hour * time.Duration(2)),
	"Europe/Budapest":                  (time.Hour * time.Duration(1)),
	"Europe/Busingen":                  (time.Hour * time.Duration(1)),
	"Europe/Chisinau":                  (time.Hour * time.Duration(2)),
	"Europe/Copenhagen":                (time.Hour * time.Duration(1)),
	"Europe/Dublin":                    time.Duration(0),
	"Europe/Gibraltar":                 (time.Hour * time.Duration(1)),
	"Europe/Guernsey":                  time.Duration(0),
	"Europe/Helsinki":                  (time.Hour * time.Duration(2)),
	"Europe/Isle_of_Man":               time.Duration(0),
	"Europe/Istanbul":                  (time.Hour * time.Duration(3)),
	"Europe/Jersey":                    time.Duration(0),
	"Europe/Kaliningrad":               (time.Hour * time.Duration(2)),
	"Europe/Kiev":                      (time.Hour * time.Duration(2)),
	"Europe/Kirov":                     (time.Hour * time.Duration(3)),
	"Europe/Lisbon":                    time.Duration(0),
	"Europe/Ljubljana":                 (time.Hour * time.Duration(1)),
	"Europe/London":                    time.Duration(0),
	"Europe/Luxembourg":                (time.Hour * time.Duration(1)),
	"Europe/Madrid":                    (time.Hour * time.Duration(1)),
	"Europe/Malta":                     (time.Hour * time.Duration(1)),
	"Europe/Mariehamn":                 (time.Hour * time.Duration(2)),
	"Europe/Minsk":                     (time.Hour * time.Duration(3)),
	"Europe/Monaco":                    (time.Hour * time.Duration(1)),
	"Europe/Moscow":                    (time.Hour * time.Duration(3)),
	"Asia/Nicosia":                     (time.Hour * time.Duration(2)),
	"Europe/Oslo":                      (time.Hour * time.Duration(1)),
	"Europe/Paris":                     (time.Hour * time.Duration(1)),
	"Europe/Podgorica":                 (time.Hour * time.Duration(1)),
	"Europe/Prague":                    (time.Hour * time.Duration(1)),
	"Europe/Riga":                      (time.Hour * time.Duration(2)),
	"Europe/Rome":                      (time.Hour * time.Duration(1)),
	"Europe/Samara":                    (time.Hour * time.Duration(4)),
	"Europe/San_Marino":                (time.Hour * time.Duration(1)),
	"Europe/Sarajevo":                  (time.Hour * time.Duration(1)),
	"Europe/Saratov":                   (time.Hour * time.Duration(4)),
	"Europe/Simferopol":                (time.Hour * time.Duration(3)),
	"Europe/Skopje":                    (time.Hour * time.Duration(1)),
	"Europe/Sofia":                     (time.Hour * time.Duration(2)),
	"Europe/Stockholm":                 (time.Hour * time.Duration(1)),
	"Europe/Tallinn":                   (time.Hour * time.Duration(2)),
	"Europe/Tirane":                    (time.Hour * time.Duration(1)),
	"Europe/Tiraspol":                  (time.Hour * time.Duration(2)),
	"Europe/Ulyanovsk":                 (time.Hour * time.Duration(4)),
	"Europe/Uzhgorod":                  (time.Hour * time.Duration(2)),
	"Europe/Vaduz":                     (time.Hour * time.Duration(1)),
	"Europe/Vatican":                   (time.Hour * time.Duration(1)),
	"Europe/Vienna":                    (time.Hour * time.Duration(1)),
	"Europe/Vilnius":                   (time.Hour * time.Duration(2)),
	"Europe/Volgograd":                 (time.Hour * time.Duration(4)),
	"Europe/Warsaw":                    (time.Hour * time.Duration(2)),
	"Europe/Zagreb":                    (time.Hour * time.Duration(1)),
	"Europe/Zaporozhye":                (time.Hour * time.Duration(2)),
	"Europe/Zurich":                    (time.Hour * time.Duration(1)),
	"GMT":                              time.Duration(0),
	"Indian/Antananarivo":              (time.Hour * time.Duration(3)),
	"Indian/Chagos":                    (time.Hour * time.Duration(6)),
	"Indian/Christmas":                 (time.Hour * time.Duration(7)),
	"Indian/Cocos":                     (time.Hour * time.Duration(6)) + (time.Minute * time.Duration(30)),
	"Indian/Comoro":                    (time.Hour * time.Duration(3)),
	"Indian/Kerguelen":                 (time.Hour * time.Duration(5)),
	"Indian/Mahe":                      (time.Hour * time.Duration(4)),
	"Indian/Maldives":                  (time.Hour * time.Duration(5)),
	"Indian/Mauritius":                 (time.Hour * time.Duration(4)),
	"Indian/Mayotte":                   (time.Hour * time.Duration(3)),
	"Indian/Reunion":                   (time.Hour * time.Duration(4)),
	"Pacific/Apia":                     (time.Hour * time.Duration(13)),
	"Pacific/Auckland":                 (time.Hour * time.Duration(12)),
	"Pacific/Bougainville":             (time.Hour * time.Duration(11)),
	"Pacific/Chatham":                  (time.Hour * time.Duration(+12)) + (time.Minute * time.Duration(45)),
	"Pacific/Chuuk":                    (time.Hour * time.Duration(10)),
	"Pacific/Easter":                   (time.Hour * time.Duration(-6)),
	"Pacific/Efate":                    (time.Hour * time.Duration(11)),
	"Pacific/Enderbury":                (time.Hour * time.Duration(13)),
	"Pacific/Fakaofo":                  (time.Hour * time.Duration(13)),
	"Pacific/Fiji":                     (time.Hour * time.Duration(12)),
	"Pacific/Funafuti":                 (time.Hour * time.Duration(12)),
	"Pacific/Galapagos":                (time.Hour * time.Duration(-6)),
	"Pacific/Gambier":                  (time.Hour * time.Duration(-9)),
	"Pacific/Guadalcanal":              (time.Hour * time.Duration(11)),
	"Pacific/Guam":                     (time.Hour * time.Duration(10)),
	"Pacific/Honolulu":                 (time.Hour * time.Duration(-10)),
	"Pacific/Johnston":                 (time.Hour * time.Duration(-10)),
	"Pacific/Kiritimati":               (time.Hour * time.Duration(14)),
	"Pacific/Kosrae":                   (time.Hour * time.Duration(11)),
	"Pacific/Kwajalein":                (time.Hour * time.Duration(12)),
	"Pacific/Majuro":                   (time.Hour * time.Duration(12)),
	"Pacific/Marquesas":                (time.Hour * time.Duration(-9)) + (time.Minute * time.Duration(30)),
	"Pacific/Midway":                   (time.Hour * time.Duration(-11)),
	"Pacific/Nauru":                    (time.Hour * time.Duration(12)),
	"Pacific/Niue":                     (time.Hour * time.Duration(-11)),
	"Pacific/Norfolk":                  (time.Hour * time.Duration(11)),
	"Pacific/Noumea":                   (time.Hour * time.Duration(11)),
	"Pacific/Pago_Pago":                (time.Hour * time.Duration(-11)),
	"Pacific/Palau":                    (time.Hour * time.Duration(9)),
	"Pacific/Pitcairn":                 (time.Hour * time.Duration(-8)),
	"Pacific/Pohnpei":                  (time.Hour * time.Duration(11)),
	"Pacific/Ponape":                   (time.Hour * time.Duration(11)),
	"Pacific/Port_Moresby":             (time.Hour * time.Duration(10)),
	"Pacific/Rarotonga":                (time.Hour * time.Duration(-10)),
	"Pacific/Saipan":                   (time.Hour * time.Duration(10)),
	"Pacific/Samoa":                    (time.Hour * time.Duration(-11)),
	"Pacific/Tahiti":                   (time.Hour * time.Duration(-10)),
	"Pacific/Tarawa":                   (time.Hour * time.Duration(12)),
	"Pacific/Tongatapu":                (time.Hour * time.Duration(13)),
	"Pacific/Truk":                     (time.Hour * time.Duration(10)),
	"Pacific/Wake":                     (time.Hour * time.Duration(12)),
	"Pacific/Wallis":                   (time.Hour * time.Duration(12)),
	"Pacific/Yap":                      (time.Hour * time.Duration(10)),
	"UTC":                              time.Duration(0),
}
